### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by d-maltos** [RootCellar/chat-app#14]
# Description
Create a retirements the txt for all the Python libraries (i.e. Tkinter) for the chat app to run so that a user can easily `pip install -f requirements.txt` and install all the app requirements.

# Done Rules:
- [ ] requirements.txt file is created in the project root.
- [ ] All necessary Python libraries are listed in the file.
- [ ] File format is correct for pip installation.
- [ ] Documentation is provided within the README.md (#15) on how to use the requirements.txt file.

**Comment by RootCellar** [comment]
We *may* not actually need this - we'll see how things go, but so far we have no dependencies besides tkinter, which seems to be built right into the Python installation.
