### ISSUE TITLE
send length of internet message before sending message

### ISSUE THREAD

**Issue by RootCellar** [RootCellar/chat-app#16]
Sending multiple internet messages rapidly may cause the recipient to receive them as one message, which can break code that isn't careful.

Will be implemented alongside #4 

- [ ] Break length of message into bytes and prepend it to the message, before sending
- [ ] Properly break apart and understand messages in recipient side

# Validation
- [ ] Code compiles without errors.
- [ ] Functions correctly as per description.
- [ ] Code is peer-reviewed.

**Comment by orlb** [comment]
Implemented in PR #30
