### ISSUE TITLE
'Join' screen

### ISSUE THREAD

**Issue by orlb** [RootCellar/chat-app#2]
Screen with input fields for server IP and username.

**Comment by RootCellar** [comment]
Keep in mind that this *does not* have to actually do anything at this stage - it just needs to be able to appear on screen.

**Comment by RootCellar** [comment]
Code should be committed and uploaded to Github repo before this can be Validated!

**Comment by orlb** [comment]
Implemented in https://github.com/RootCellar/chat-app/commit/cb2e4221cc8e7999e048ab74af3c5b1a7a1d6995.
