### ISSUE TITLE
'Chat' screen

### ISSUE THREAD

**Issue by orlb** [RootCellar/chat-app#3]
Screen with input field for message, 'submit' button, and chat history canvas.

**Comment by RootCellar** [comment]
Keep in mind that this *does not* have to actually do anything at this stage - it just needs to be able to appear on screen.

**Comment by RootCellar** [comment]
Code should be committed and uploaded to Github repo before this can be Validated!

**Comment by orlb** [comment]
Implemented in cb2e422
