### ISSUE TITLE
implement internet message ID codes

### ISSUE THREAD

**Issue by RootCellar** [RootCellar/chat-app#4]
Implement codes that are sent as part of a complete message that say what kind of message it is. This allows the client and server to communicate in more than just chat messages, which gives us the ability to implement other features.

Requires #7 and #8 to be completed.

Will be implemented alongside #16 

- [ ] Break type of message into bytes and prepend it to the message, before sending
- [ ] Properly break apart and understand messages in recipient side

# Validation
- [ ] Code compiles without errors.
- [ ] Functions correctly as per description.
- [ ] Code is peer-reviewed.

**Comment by orlb** [comment]
Implemented in PR #30
